### ISSUE TITLE
start capturing video but not able to capture video just display black screen.

### ISSUE THREAD

**Issue by akshay-shah-dev** [Yummypets/YPImagePicker#404] opened 2019-10-08 09:54 UTC
**Describe the bug**
i am capturing video for open first capture image and click on button video but video not capturing just display black screen.

**Environment (please complete the following information):**
 - Device: [iphone 6 version 12.2]
 - OS: [10.14.5]
 - Xcode Version [10.1]
 - Swift Version [4.1]

**Installation Type**
 - Cocoapods

**Comment by parveen702** [comment] 2020-01-02 11:29
I have same issue

**Comment by s4cha** [comment] 2020-01-03 09:21
I have the same issue as well. This seems to happen randomly, looks like a threading issue. If you have any details or if you find ways to reproduce it, please share as much details as possible so we can fix it.

**Comment by parveen702** [comment] 2020-01-06 06:22
It can be reproduce easily and frequently. Just switch form photo capture to video capture. You will find video screen stuck.
Kind Regards

Parveen Khan | iOS Application Developer
Dotsquares Ltd "Celebrating 16 Years of Success"
T: +44 (0) 1273 900273 | T: +44 (0) 1273 900296 | W: www.dotsquares.com <http://www.dotsquares.com/> | Skype: parveen.khan@dotsquares.com <mailto:krishan.kumar@dotsquares.com>

**Comment by taimoorsuleman** [comment] 2020-01-06 09:22
I have the same issue and reproduced frequently.
Just switch tabs from photo to video.

**Comment by parveen702** [comment] 2020-01-06 10:56
i have resolved this issue on calling video start function after some delay
DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                videoVC.start()
            }

**Comment by ashisht85** [comment] 2020-06-18 13:17
Hi Sir,
I am using YPImagePicker Library in our iOS Swift 4 code App. but in this library I am facing a major issue. when we capture video from android device and upload/load this video via YPImagePicker Library to our app. then this Library is showing black cover image and Thumbnail image. while this video is properly working on android device. here we are attaching some screen shot where this library is showing black cover image and thumbnail. please check and tell me where is the issue. thanks in advance for solution
![BlackScreen](https://user-images.githubusercontent.com/3831786/85023631-9fa5b480-b192-11ea-91de-f61056415649.png)
![BlackCoverImg](https://user-images.githubusercontent.com/3831786/85023783-d1b71680-b192-11ea-91bb-454686d257bd.png)



Thanks
Ashish Tiwari
ashishtiwari0910@gmail.com
9013590964

**Comment by NikKovIos** [comment] 2022-01-08 15:13
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮

**Closed as completed by NikKovIos** 2022-01-08 15:13 UTC
