### ISSUE TITLE
Images from ".album" are at the very end of the gallery

### ISSUE THREAD

**Issue by mcaldas** [Yummypets/YPImagePicker#281] opened 2018-12-07 23:40 UTC
**Describe the bug**
When selecting images from `PHAssetCollection` two types of albums are selected `.album` and `.smartAlbum` in 2 different arrays, separately and joined in a loop.
Problem is that regular `.album` results get at the very end of the array, so they are shown at the end of the gallery, even though the creation time is newer 

**To Reproduce**
0. Make sure you save an image that doesnt take part of a smart album (PNG for example)
1. Go to 'gallery'
2. That image doesnt appears
3. Scroll down to very bottom of the gallery (good luck if u have thousands of images)
4. See error, only there u see the image u are looking for

**Expected behavior**
.albums and .smartAlbums should be merged respecting the image creation date

**Environment (please complete the following information):**
 - Device: [iPhone8]
 - OS: [iOS12]
 - Xcode Version [e.g. 10]
 - Swift Version [e.g. 4.2]

**Installation Type**
 - Cocoapods

**Comment by s4cha** [comment] 2018-12-10 10:52
Hi @mcaldas 
This looks like a bug indeed, thanks for taking the time to write and issue 👍 
I can't seem to reproduce it on my side though.
By default, the media request has as `creationDate` sort.
```swift
options.sortDescriptors = [NSSortDescriptor(key: "creationDate", ascending: false)]
```
Are you by any chance using a non null `config.library.options` ? (which would override the default)

Saving a PNG from safari works great on my side, does the issue also happens in that case for you?

**Comment by mcaldas** [comment] 2018-12-10 14:31
Hey @s4cha ,
Nope I dont use `config.library.options` anywhere.
I didnt try from safari, tried from telegram, but the thing is that specific image i see it "All Photos" album but not in "Photos" so my guess was something there

**Comment by NikKovIos** [comment] 2022-01-08 12:44
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮

**Closed as completed by NikKovIos** 2022-01-08 12:44 UTC
