### ISSUE TITLE
After selecting the normal filter in the filters list 

### ISSUE THREAD

**Issue by pdee2131** [Yummypets/YPImagePicker#332] opened 2019-04-11 13:51 UTC
**Describe the bug**
After selecting the normal filter in the filter section, the selected image fails to select. WHen any other filter is selected it works well but only the normal filter fails to work.

1 a: After selecting Normal FIlter LIke Below

![Screenshot 2019-04-11 at 13 40 00](https://user-images.githubusercontent.com/10502787/55961999-94d2c400-5c5f-11e9-9f26-ee5816b2e813.png)

b: 
![Screenshot 2019-04-11 at 13 40 14](https://user-images.githubusercontent.com/10502787/55962061-b764dd00-5c5f-11e9-9a32-5d200b2078e0.png)

2 a: Then selecting any other filter works perfectly like this
![Screenshot 2019-04-11 at 13 41 18](https://user-images.githubusercontent.com/10502787/55962516-9355cb80-5c60-11e9-9e23-5e64df8be718.png)

b: After selecting it shows perfectly
![Screenshot 2019-04-11 at 13 41 36](https://user-images.githubusercontent.com/10502787/55962572-b1233080-5c60-11e9-971c-c052c50f708a.png)

Am using swift 4.2 with the respective YPImagePicker cocoapods version

**Comment by s4cha** [comment] 2019-04-28 13:11
@pdee2131 wow that is a very weird bug, I unfortunately couldn't reproduce it on my side, could you try to investigate what's happening in the code a little further?

**Comment by s4cha** [comment] 2019-12-20 10:01
@pdee2131 are you still having this issue?

**Comment by NikKovIos** [comment] 2022-01-08 12:46
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮

**Closed as completed by NikKovIos** 2022-01-08 12:46 UTC
