### ISSUE TITLE
ios13.1 can't find nextbutton in filterpage 

### ISSUE THREAD

**Issue by jinjinbary** [Yummypets/YPImagePicker#419] opened 2019-11-08 02:35 UTC
ios 13.1
i can't find nextbutton in filterselectpage

**Comment by Emefar** [comment] 2019-11-09 11:22
@NikKovIos Please answer. I cannot find too. I cannot save photos.

**Comment by jinjinbary** [comment] 2019-11-11 05:52
This problem is due to ios 13.1 dark mode.
 inpo.list -> user interface style -> light
This solves the problem.

**Comment by NikKovIos** [comment] 2019-11-27 18:22
The problem is because of color.

**Comment by s4cha** [comment] 2019-12-11 10:10
@jinjinbary @Emefar Cant you try to reproduce your issue with the sample project from master? this should be fixed with the dark mode support coming in the next version :)

**Comment by Emefar** [comment] 2019-12-11 16:16
@s4cha I think is not relevant dark mode. I am not using dark mode. Btw i am using force white mode.

**Comment by NikKovIos** [comment] 2022-01-08 15:13
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮

**Closed as completed by NikKovIos** 2022-01-08 15:13 UTC
