### ISSUE TITLE
Image picker closes unexpectedly with "Picker deinited 👍"  in debug window when click on "Gallery", if phone gallery is empty.

### ISSUE THREAD

**Issue by farhan101** [Yummypets/YPImagePicker#292] opened 2018-12-24 09:59 UTC
Image picker closes unexpectedly with "Picker deinited 👍"  in debug window when click on "Gallery", if phone gallery is empty.

iPhone - 6s plus
iOS - 12.0.1

**Comment by s4cha** [comment] 2018-12-28 15:45
@farhan101 Very good catch, looking at it at the moment :)

**Comment by farhan101** [comment] 2019-01-01 08:37
> @farhan101 Very good catch, looking at it at the moment :)

Great, thanks.

**Comment by neodave** [comment] 2019-08-02 19:54
Was this ever resolved? Still an issue

**Comment by neodave** [comment] 2019-08-02 21:59
After looking at this more closely it is a feature not a bug. There is delegate function noPhotos that is called. Inside YPPickerVC is where that delegate method is called, and that is where the dismiss is. Removing that will stop the instant dismissal. Now the question is how to switch to the camera if no photos are in the library

**Comment by NikKovIos** [comment] 2022-01-08 12:44
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮

**Closed as completed by NikKovIos** 2022-01-08 12:44 UTC
