### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by ProKashif** [Yummypets/YPImagePicker#472] opened 2020-03-27 13:57 UTC
**Describe the bug**
App Crash on Camera capture click 

**To Reproduce**
1. Go to 'Open Camera'
2. Click on 'click camera capture photo button'

**Expected behavior**
Fatal Exception: NSGenericException
0  CoreFoundation                 0x204220ec4 __exceptionPreprocess
1  libobjc.A.dylib                0x2033f1a50 objc_exception_throw
2  AVFoundation                   0x20a3b9b48 -[AVCapturePhotoOutput capturePhotoWithSettings:delegate:]
3  YPImagePicker                  0x1058b4db0 (Missing)
4  YPImagePicker                  0x1058c66b8 (Missing)
5  YPImagePicker                  0x1058c642c (Missing)
6  YPImagePicker                  0x1058c6700 (Missing)

**Screenshots**
<img width="996" alt="Screenshot 2020-03-27 at 6 54 58 PM" src="https://user-images.githubusercontent.com/33416799/77763358-c1444380-705c-11ea-908b-58f5d1caa06d.png">

<img width="959" alt="Screenshot 2020-03-27 at 7 00 03 PM" src="https://user-images.githubusercontent.com/33416799/77763632-3152c980-705d-11ea-8652-54f5eb66e4f3.png">

**Comment by ahmedsafadii** [comment] 2020-05-10 23:43
same for me

**Comment by NikKovIos** [comment] 2021-08-14 23:24
Duplicate of https://github.com/Yummypets/YPImagePicker/issues/610

**Closed as completed** 2021-08-14 23:25 UTC
