### ISSUE TITLE
Rotation on iPad broke all UI

### ISSUE THREAD

**Issue by thierrybucco** [Yummypets/YPImagePicker#426] opened 2019-11-26 20:37 UTC
Display camera view on iPad, then rotate it.
![IMG_0622](https://user-images.githubusercontent.com/12764744/69670777-aa67f300-1062-11ea-9f0c-caa27a1e6413.PNG)

**Comment by s4cha** [comment] 2019-12-11 14:49
@thierrybucco Nice catch. The picker only works in portrait mode, we need to lock its orientation from our side. This will be fixed in next version :)

**Comment by s4cha** [comment] 2019-12-11 15:03
Well forcing `supportedInterfaceOrientations` to `portrait` in `YPImagePicker` works for phones but the orientation callbacks are not called on iPads. No idea at the moment so it will not make it to the next version unfortunately

**Comment by RobSwish** [comment] 2019-12-18 19:28
I've had issues like this before with iPad in landscape, to make it at least useable instead of completely broken perhaps you could just make the views left and right constraints based around the readable content guides on iPad. 

This way it will be heavily inset on iPad but it should at least make it look decent and be functional 🙂 

Of course the swipe animation won't be as nice too, but still. I'll be giving this a go myself at some point so I'll let you know how it goes.

That said, this may only be okay when the camera is square. hmmmm....

**Comment by BillBunting** [comment] 2020-08-16 01:19
Still an issue also with selecting photos. I receive support requests from users indicating they can not select multiple photos on iPad.  It turns out, it is because they are in landscape orientation (confirmed on iPad 2 model A1566 iOS 13.6 in simulator).

**Comment by NikKovIos** [comment] 2022-01-08 15:12
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮

**Closed as completed by NikKovIos** 2022-01-08 15:12 UTC
Labels: Bug
